version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: agenda_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: agenda_express
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: docker
    container_name: agenda_backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/agenda_express
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

      JWT_SECRET: MINHA_CHAVE_SECRETA_64_CHARS

    ports:
      - "8080:8080"
    restart: always

volumes:
  postgres_data:
